### ISSUE TITLE
Angular 16

### ISSUE THREAD

**Issue by nish-d** [dkreider/ngx-loading-buttons#19]
I'm unable to get the library to work on my Application running with Angular 16

Error:
```

Uncaught TypeError: Cannot set property elementClass of [object Object] which has only a getter
    at writeToDirectiveInput (core.mjs:12872:34)
    at setInputsForProperty (core.mjs:13106:9)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:16251:5)
    at ɵɵelementEnd (core.mjs:16358:9)
    at BerthChartComponent_div_1_button_16_Template (template.html:52:7)
    at executeTemplate (core.mjs:11986:13)
    at renderView (core.mjs:13184:13)
    at createAndRenderEmbeddedLView (core.mjs:23961:5)
    at TemplateRef.createEmbeddedViewImpl (core.mjs:24047:31)
    at ViewContainerRef.createEmbeddedView (core.mjs:24355:37)
```

**Comment by dkreider** [comment]
Hey @nish-d thanks for opening an issue.

I'm using vs 16.2.8 and am unable to reproduce the issue.

![image](https://github.com/dkreider/ngx-loading-buttons/assets/11043868/c72fe305-936a-4d4c-b754-4626d2a5f472)

Mind giving some more details or better yet tell me how to reproduce this?
